POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{ 
    "title": "Stanjy post",
    "author": "Stanimal",
    "url": "https://www.amazinavenue.com/2021/6/14/22532886/mets-jacob-degrom-2021-stats-10-starts-history-seaver-gooden-pedro",
    "likes": 74
}