POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVyaWNjaG9pMjEyIiwiaWQiOiI2MGNkOTQ3ZTljMzYyYjkzNjVjZjZkMzIiLCJpYXQiOjE2MjQxMjU2NTZ9.y2xNJmTCwoDr3W1obhHIuDv0pL3U8ByGy3cGB_eTrtw

{ 
    "title": "Eric's fav blog post",
    "author": "Eric Choi",
    "url": "https://progolfnow.com/2021/06/18/2021-u-s-open-five-storylines-watch-saturday/",
    "likes": 69
}